// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdXvkCeizF9BNhaUFNFxZOLLZ3dQ4Bz1Y',
    appId: '1:299793825184:web:a4f5fd7f124a94b8a8b8c5',
    messagingSenderId: '299793825184',
    projectId: 'torogo-d5d82',
    authDomain: 'torogo-d5d82.firebaseapp.com',
    storageBucket: 'torogo-d5d82.appspot.com',
    measurementId: 'G-N5KC8K9NBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0V5J1JybUkQoG6XEma3Gcr7EeMEcCfe0',
    appId: '1:299793825184:android:e0f726594788efa8a8b8c5',
    messagingSenderId: '299793825184',
    projectId: 'torogo-d5d82',
    storageBucket: 'torogo-d5d82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtl9GdXn0MqF3Cjk_EvNrfUlPv9ZfvXoo',
    appId: '1:299793825184:ios:7d6f6d7dc8a73a33a8b8c5',
    messagingSenderId: '299793825184',
    projectId: 'torogo-d5d82',
    storageBucket: 'torogo-d5d82.appspot.com',
    iosBundleId: 'com.example.togosv01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtl9GdXn0MqF3Cjk_EvNrfUlPv9ZfvXoo',
    appId: '1:299793825184:ios:d73280f247796dd4a8b8c5',
    messagingSenderId: '299793825184',
    projectId: 'torogo-d5d82',
    storageBucket: 'torogo-d5d82.appspot.com',
    iosBundleId: 'com.example.togosv01.RunnerTests',
  );
}
